#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/FocuserPlugIns/"

if [ ! -d "$PLUGINS_DIR/WeatherStationPlugIns/" ]; then
    mkdir "$PLUGINS_DIR/WeatherStationPlugIns/"
fi

cp -f "/tmp/SoloCloudwatcher_X2/weatherstationlist SoloCloudwatcher.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/WeatherStationPlugIns/libSoloCloudwatcher.dylib"
cp "/tmp/SoloCloudwatcher_X2/libSoloCloudwatcher.dylib" "$PLUGINS_DIR/WeatherStationPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/WeatherStationPlugIns/SoloCloudwatcher.ui"
cp "/tmp/SoloCloudwatcher_X2/SoloCloudwatcher.ui" "$PLUGINS_DIR/WeatherStationPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/weatherstationlist SoloCloudwatcher.txt"
	chown $app_owner "$PLUGINS_DIR/WeatherStationPlugIns/libSoloCloudwatcher.dylib"
	chown $app_owner "$PLUGINS_DIR/WeatherStationPlugIns/SoloCloudwatcher.ui"
fi

rm -rf /tmp/SoloCloudwatcher_X2

